### ISSUE TITLE
mt103

### ISSUE THREAD

**Issue by studentforcode** [danielquinn/mt103#14]
Hello,
i would have ried to run this sript it couldnt work , 

![mt103](https://github.com/danielquinn/mt103/assets/92729101/fee11a65-8c33-4199-93f0-0bf8029fc7b6)

**Comment by studentforcode** [comment]
I dont really know if its from my site in install and runing the scripts .

**Comment by nanorepublica** [comment]
This library isn't meant to be run directly. See the Readme on how to import it and use it.

**Comment by studentforcode** [comment]
Thanks for your help, I read  and still couldn't do that , any way someone can me more better ?

**Comment by nanorepublica** [comment]
You haven't described what you tried to do...

**Comment by studentforcode** [comment]
All I need is to run the program I mean , like to send fund

**Comment by nanorepublica** [comment]
I doubt that the script in that video is the same as this library. 

This isn't a script you just run. You need to write your own script that uses this library

**Comment by nanorepublica** [comment]
No and I am closing this issue. There isn't a problem with the library.

**Comment by studentforcode** [comment]
Ok thank you
