### ISSUE TITLE
Optional user_header causes repr() issues

### ISSUE THREAD

**Issue by bradenneal1** [danielquinn/mt103#5]
When a message does not provide a user header (3), the resulting MT103 object cannot be output. For example, taking `MESSAGE1` from your test files produces the following error:

```
>>> MT103(MESSAGE1).user_header
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mt103.py", line 120, in __repr__
    return str(self)
TypeError: __str__ returned non-string (type NoneType)
```

This could be solved simply by treating the group as optional i.e.
change:
```
self.user_header = UserHeader(m.group("user_header"))
```
to:
```
self.user_header = UserHeader(m.group("user_header") or "")
```

**Comment by danielquinn** [comment]
I know I'm late to the party on this one, but thanks for finding this and even suggesting a fix!  I've made the required changes to `master` and will push out an update to PyPI today.
